server:
  # 配置端口号
  port: 8011
spring:
  # 配置mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wong_store?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # 配置redis
  data:
    redis:
      host: localhost
      port: 6379
    # password:
# 配置mybatis
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml
# 配置放行url
store:
  auth:
    no-auth-urls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode
      - /doc.html
      - /webjars/**
      - /v3/**
  minio:
    endpoint-url: http://192.168.2.140:9000
    access-key: minio
    secret-key: password
    bucket-name: store-bucket