server:
  port: 8831
spring:
  application:
    name: service-user
  cloud:
    # 配置nacos
    nacos:
      discovery:
        server-addr: localhost:8848
  # 配置mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wong_store?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    # 配置redis
    redis:
      host: localhost
      port: 6379
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml